# http服务端口
server:
  port: 6070

# dubbo相关
dubbo:
  application:
    name: dubbo-demo-service-manager
  registry:
    address: zookeeper://47.101.135.160:2181 # 注册中心地址
  config-center:
    address: zookeeper://47.101.135.160:2181 # 配置中心地址
  metadata-report:
    address: zookeeper://47.101.135.160:2181 # 元数据中心地址
  # scan:
  #  base-packages: com.jinhaoxun.dubbod.service # 扫描提供服务的路径，启动类加上@EnableDubbo时，可以不需要这个
  protocol:
    name: dubbo
    port: -1 # 服务在dubbo中端口号,-1代表自动分配
  monitor:
    protocol: registry # 自动注册dubbo的monitor
  consumer:
    check: false # 启动检查有没有提供者
    timeout: 12000 # 消费者调用超时时间
    retries: 1 # 调用失败重试次数，不包含第一次调用
    version: 1.0.0 # 统一调用版本服务，实现灰度发布
    loadbalance: roundrobin # 负载均衡。random：权重随机，roundrobin：权重轮询，leastactive：速度最快优先，consistenthash：一致性哈希
  provider:
    version: 1.0.0 # 统一调用版本服务，实现灰度发布

# 配置mybatis-plus
mybatis-plus:
  # xml映射文件位置，衔接pom文件里面的resources配置扫描
  mapper-locations: classpath*:com/jinhaoxun/dubbo/mapper/**/xml/*.xml
  # type-aliases-package: com.jinhaoxun.accommon.pojo # 别名包扫描路径，通过该属性可以给包中的类注册别名
  # configuration:
  cache-enabled: true # 开启MybatisPlus 二级缓存，主要用来跟redis注解缓存使用
  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 开启MybatisPlus SQL日志打印

# spring相关
spring:
  aop:
    auto: true # 开启spring aop

  cache:
    type: redis # 指定spring缓存为redis

  datasource: # 配置mysql
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql数据库驱动
    password: root
    url: jdbc:mysql://47.101.135.160:3306/dubbo_demo?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root

  devtools: # spirng热部署
    restart:
      enabled: true # 设置开启热部署
      additional-paths: src/main/java # 重启目录
      exclude: WEB-INF/**

  redis:
    database: 0 # redis 数据库索引（默认为0）
    host: 47.101.135.160
    password: root # redis 服务器连接密码（默认为空）
    port: 6379
    timeout: 12000  # 连接超时时间（毫秒），默认2000ms
      # cluster:
      # nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
    # maxRedirects: 6
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

# 配置rabbitmq
rabbitmq:
  host: 47.101.135.160
  port: 15672
  username: admin
  password: admin
  publisher-confirms: true
  publisher-returns: true
  virtual-host: /

# 配置stomprabbitmq
stomprabbitmq:
  relayhost: 47.101.135.160
  port: 61613

# 打印日志统一根路径
log:
  file: /Users/ao/Documents/log/dubbo-demo/service-manager