FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY dubbo-demo-web-1.0.0-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 6060
EXPOSE 6061
EXPOSE 6062
EXPOSE 8440
EXPOSE 8441
EXPOSE 8442
ENV PROFILES="prod-6060+8440"
ENTRYPOINT ["sh","-c","java -jar app.jar --spring.profiles.active=$PROFILES "]
# docker build -t dubbo-demo-web .
# docker run -dit --name dubbo-demo-web-6060 -v /usr/local/docker/dubbo/log/dubbo-web-6060+8440/:/usr/local/service/log/dubbo-demo-web/6060+8440/ -p 6060:6060 -p 8440:8440 -e PROFILES="prod-6060+8440" dubbo-demo-web
# docker run -dit --name dubbo-demo-web-6061 -v /usr/local/docker/dubbo/log/dubbo-web-6061+8441/:/usr/local/service/log/dubbo-demo-web/6061+8441/ -p 6061:6061 -p 8441:8441 -e PROFILES="prod-6061+8441" dubbo-demo-web
# docker run -dit --name dubbo-demo-web-6062 -v /usr/local/docker/dubbo/log/dubbo-web-6062+8442/:/usr/local/service/log/dubbo-demo-web/6062+8442/ -p 6062:6062 -p 8442:8442 -e PROFILES="prod-6062+8442" dubbo-demo-web