FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY dubbo-demo-service-manager-1.0.0-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 6070
EXPOSE 6071
EXPOSE 6072
ENV PROFILES="prod-6070"
ENTRYPOINT ["sh","-c","java -jar app.jar --spring.profiles.active=$PROFILES "]
# docker build -t dubbo-demo-service-manager .
# docker run -dit --name dubbo-demo-service-manager-6070 -v /usr/local/docker/dubbo/log/dubbo-service-manager-6070/:/usr/local/service/log/dubbo-demo-service-manager/6070/ -v /usr/local/docker/dubbo/file/:/usr/local/service/file/ -p 6070:6070 -e PROFILES="prod-6070" dubbo-demo-service-manager
# docker run -dit --name dubbo-demo-service-manager-6071 -v /usr/local/docker/dubbo/log/dubbo-service-manager-6071/:/usr/local/service/log/dubbo-demo-service-manager/6071/ -v /usr/local/docker/dubbo/file/:/usr/local/service/file/ -p 6071:6071 -e PROFILES="prod-6071" dubbo-demo-service-manager
# docker run -dit --name dubbo-demo-service-manager-6072 -v /usr/local/docker/dubbo/log/dubbo-service-manager-6072/:/usr/local/service/log/dubbo-demo-service-manager/6072/ -v /usr/local/docker/dubbo/file/:/usr/local/service/file/ -p 6072:6072 -e PROFILES="prod-6072" dubbo-demo-service-manager