# docker pull redis:4.0
# docker run -dit --name redis-4.0 -p 6379:6379 -v /usr/local/docker/redis/data:/data redis:4.0 redis-server --appendonly yes --requirepass "root"
# docker exec -it redis-4.0 bash
version: '3.7'
services:
  redis:
    image: redis:4.0
    restart: always
    container_name: redis
    command: redis-server --appendonly yes --requirepass "root"
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 6379:6379
    volumes:
      - /usr/local/docker/redis/data:/data