FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY dubbo-admin-server-0.1.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 9090
ENTRYPOINT ["java", "-jar", "app.jar"]
# docker build -t dubbo-admin-9090 .
# docker run -dit --name dubbo-admin-9090 -p 9090:9090 dubbo-admin-9090