# docker pull nginx:1.16.1
# docker run -dit --name nginx-1.16.1 -p 80:80 -p 8443:8443 -v /usr/local/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf -v /usr/local/docker/nginx/logs:/var/log/nginx -v /usr/local/docker/nginx/html:/etc/nginx/html -v /usr/local/docker/nginx/conf/2137274_apecome.top.key:/etc/nginx/2137274_apecome.top.key  -v /usr/local/docker/nginx/conf/2137274_apecome.top.pem:/etc/nginx/2137274_apecome.top.pem nginx:1.16.1
version: '3.7'
services:
  nginx:
    image: nginx:1.16.1
    restart: always
    container_name: nginx
    environment:
      TZ: 'Asia/Shanghai'
    ports:
      - 80:80
      - 8443:8443
    volumes:
      - /usr/local/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/local/docker/nginx/logs:/var/log/nginx
      - /usr/local/docker/nginx/html:/etc/nginx/html
      - /usr/local/docker/nginx/conf/2137274_apecome.top.key:/etc/nginx/2137274_apecome.top.key # ssl证书
      - /usr/local/docker/nginx/conf/2137274_apecome.top.pem:/etc/nginx/2137274_apecome.top.pem