# docker pull gitlab/gitlab-ce
# docker run -d -p 444:443 -p 88:80 -p 222:22 --name gitlab --restart always -v /usr/local/gitlab/config:/etc/gitlab -v /usr/local/gitlab/logs:/var/log/gitlab -v /usr/local/gitlab/data:/var/opt/gitlab gitlab/gitlab-ce
# -d：后台运行
# -v：将容器内数据文件夹或者日志、配置等文件夹挂载到宿主机指定目录

# gitlab.rb文件内容默认全是注释
# vim /home/gitlab/config/gitlab.rb
# 配置http协议所使用的访问地址,不加端口号默认为80
# external_url 'http://172.16.31.130:88'
# 配置ssh协议所使用的访问地址和端口
# gitlab_rails['gitlab_ssh_host'] = '172.16.31.130'
# 此端口是run时22端口映射的222端口
# gitlab_rails['gitlab_shell_ssh_port'] = 222
version: '3.7'
services:
  gitlab:
    image: gitlab/gitlab-ce
    restart: always
    container_name: gitlab
    hostname: 172.16.31.130
    environment:
      TZ: 'Asia/Shanghai'
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://172.16.31.130:88'
        gitlab_rails['gitlab_shell_ssh_port'] = 222
        gitlab_rails['time_zone'] = 'Asia/Shanghai'
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "smtp.aliyun.com"
        gitlab_rails['smtp_port'] = 465
        gitlab_rails['smtp_user_name'] = "luoyusoft@126.com"  #用自己的aliyun邮箱
        gitlab_rails['smtp_password'] = "axbc1kof"
        gitlab_rails['smtp_domain'] = "aliyun.com"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = true
        gitlab_rails['smtp_tls'] = true
        gitlab_rails['gitlab_email_from'] = 'luoyusoft@126.com'
        gitlab_rails['gitlab_shell_ssh_port'] = 222
    ports:
      - 88:80
      - 444:443
      - 222:22
    volumes:
      - /usr/local/docker/gitlab/config:/etc/gitlab
      - /usr/local/docker/gitlab/data:/var/opt/gitlab
      - /usr/local/docker/gitlab/logs:/var/log/gitlab