# docker pull mysql:5.7
  # docker run -dit --name mysql-5.7 -p 3306:3306 -v /usr/local/docker/mysql/data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mysql:5.7 --lower_case_table_names=1
# docker exec -it mysql-5.7 bash
version: '3.7'
services:
  mysql:
    image: mysql:5.7
    restart: always
    #这行代码解决无法访问的问题
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: root
      lower_case_table_names: 1
    ports:
      - 3306:3306
    volumes:
      - /usr/local/docker/mysql/data:/var/lib/mysql