version: '3.7'
services:
  namesrv:
    image: rocketmqinc/rocketmq
    container_name: rmqnamesrv
    ports:
      - 9876:9876
    volumes:
      - /usr/local/docker/rocketmq/logs:/home/rocketmq/logs
      - /usr/local/docker/rocketmq/store:/home/rocketmq/store
      - /usr/local/docker/rocketmq/bin/runserver.sh:/opt/rocketmq-4.4.0/bin/runserver.sh
      - /etc/localtime:/etc/localtime:ro # 修改容器内的时区和宿主机一样
    command: sh mqnamesrv

  broker:
    image: rocketmqinc/rocketmq
    container_name: rmqbroker
    ports:
      - 10909:10909
      - 10911:10911
      - 10912:10912
    volumes:
      - /usr/local/docker/rocketmq/logs:/home/rocketmq/logs
      - /usr/local/docker/rocketmq/store:/home/rocketmq/store
      - /usr/local/docker/rocketmq/conf/broker.conf:/opt/rocketmq-4.4.0/conf/broker.conf
      - /usr/local/docker/rocketmq/bin/runbroker.sh:/opt/rocketmq-4.4.0/bin/runbroker.sh
      - /etc/localtime:/etc/localtime:ro # 修改容器内的时区和宿主机一样
    #command: sh mqbroker -n namesrv:9876
    command: sh mqbroker -n namesrv:9876 -c ../conf/broker.conf
    depends_on:
      - namesrv
    environment:
      - JAVA_HOME=/usr/lib/jvm/jre

  console:
    image: styletang/rocketmq-console-ng
    container_name: rocketmq-console-ng
    volumes:
      - /etc/localtime:/etc/localtime:ro # 修改容器内的时区和宿主机一样
    ports:
      - 9875:8080
    depends_on:
      - namesrv
    environment:
      - JAVA_OPTS= -Dlogging.level.root=info   -Drocketmq.namesrv.addr=rmqnamesrv:9876
      - Dcom.rocketmq.sendMessageWithVIPChannel=false