FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY dubbo-admin-0.0.1-SNAPSHOT.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 9091
ENTRYPOINT ["java", "-jar", "app.jar"]
# docker build -t dubbo-admin-9091 .
# docker run -dit --name dubbo-admin-9091 -p 9091:9091 dubbo-admin-9091