FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY rocketmq-console-ng-1.1.0.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 9875
ENTRYPOINT ["java", "-jar", "app.jar"]
# docker build -t rocketmq-console-9875 .
# docker run -dit --name rocketmq-console-9875 -p 9875:9875 rocketmq-console-9875