FROM java:8
MAINTAINER jinhaoxun
VOLUME /tmp
COPY dubbo-demo-service-1.0.0.jar app.jar
RUN bash -c 'touch /app.jar'
EXPOSE 6050
EXPOSE 6051
EXPOSE 6052
ENV PROFILES="prod-6050"
ENTRYPOINT ["sh","-c","java -jar app.jar --spring.profiles.active=$PROFILES "]
# docker build -t dubbo-demo-service .
# docker run -dit --name dubbo-demo-service-6050 -v /usr/local/docker/dubbo/log/dubbo-service-6050/:/usr/local/service/log/dubbo-demo-service/ -p 6050:6050 -e PROFILES="prod-6050" dubbo-demo-service
# docker run -dit --name dubbo-demo-service-6051 -v /usr/local/docker/dubbo/log/dubbo-service-6051/:/usr/local/service/log/dubbo-demo-service/ -p 6051:6051 -e PROFILES="prod-6051" dubbo-demo-service
# docker run -dit --name dubbo-demo-service-6052 -v /usr/local/docker/dubbo/log/dubbo-service-6052/:/usr/local/service/log/dubbo-demo-service/ -p 6052:6052 -e PROFILES="prod-6052" dubbo-demo-service