# nginx
docker pull nginx:1.16.1
docker run -dit --name nginx-1.16.1 -p 80:80 -p 8443:8443 -v /usr/local/docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf  -v /usr/local/docker/nginx/logs:/var/log/nginx -v /usr/local/docker/nginx/html:/etc/nginx/html -v /usr/local/docker/nginx/conf/2137274_apecome.top.key:/etc/nginx/2137274_apecome.top.key  -v /usr/local/docker/nginx/conf/2137274_apecome.top.pem:/etc/nginx/2137274_apecome.top.pem nginx:1.16.1
