debug: true

#服务名称
dubbo:
  application:
    name: dubbo-demo-service
  #注册中心地址
  registry:
    address: zookeeper://47.101.135.160:2181
  #扫描提供服务的路径
  #scan:
  #  base-packages: com.jinhaoxun.dubbod.service
  protocol:
    name: dubbo
    #服务在dubbo中端口号
    port: 20881
  monitor:
    protocol: registry

# http 服务端口
server:
  port: 6061

mybatis-plus:
  # xml映射文件位置，衔接pom文件里面的resources配置扫描
  mapper-locations: classpath*:/mapper/apply/xml/*.xml,classpath*:/mapper/quartz/xml/*.xml,classpath*:/mapper/shiro/xml/*.xml
  # 别名包扫描路径，通过该属性可以给包中的类注册别名
  # type-aliases-package: com.jinhaoxun.accommon.pojo
  # configuration:
  # 开启 MybatisPlus 二级缓存，主要用来跟redis注解缓存使用
  # cache-enabled: true
  # 开启 MybatisPlus SQL日志打印
  # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  devtools:
    restart:
      enabled: true  #设置开启热部署
  # spirng 热部署
  # 开启 spring aop
  # aop:
  # auto: true
  # 指定 spring 缓存为 redis
  # cache:
  # type: redis
  # 配置数据库
  datasource:
    # mysql 数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    url: jdbc:mysql://47.101.135.160:3306/apecome?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
  # 开启 spring aop
  # aop:
  # auto: true
  # 指定 spring 缓存为 redis
  # cache:
  # type: redis

  # 配置数据库
  redis:
    # redis 数据库索引（默认为0）
    database: 0
    # redis 服务器地址
    host: 47.101.135.160
    # redis 服务器连接密码（默认为空）
    password: root
    # redis 服务器连接端口
    port: 6379
    # 连接超时时间（毫秒）
    timeout: 0
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 500
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-wait: -1ms

threadPoolTaskExecutor:
  corePoolSize: 10
  maxPoolSize: 100
  keepAliveTime: 10
  queueCapacity: 200
  threadNamePrefix: Async-Executor-

rocketmq:
  producer:
    groupname: serviceProducerGroup
    maxmessagesize: 131072
    sendmsgtimeout: 10000
    # instanceName: 实例名
  consumer:
    groupname: serviceConsumerGroup
    topicname: service
    consumethreadmin: 20
    consumethreadmax: 64
  namesrvaddr: 47.101.135.160:9876

rabbitmq:
  host: 47.101.135.160
  port: 15672
  username: admin
  password: admin
  publisher-confirms: true
  publisher-returns: true
  virtual-host: /

stomprabbitmq:
  relayhost: 47.101.135.160
  port: 61613

file:
  upload:
    path: /usr/local/file/
  download:
    path: /usr/local/file/

log:
  file: log
