# http服务端口
server:
  port: 6060

# 安全停机配置
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  server:
    port: 6060

knife4j:
  production: false
  basic:
    enable: true
    username: root
    password: root

# dubbo相关
dubbo:
  application:
    name: dubbo-demo-web
  registry:
    address: zookeeper://47.101.135.160:2181 # 注册中心地址
  config-center:
    address: zookeeper://47.101.135.160:2181 # 配置中心地址
  metadata-report:
    address: zookeeper://47.101.135.160:2181 # 元数据中心地址
  # scan:
  #  base-packages: com.jinhaoxun.dubbod.service # 扫描提供服务的路径，启动类加上@EnableDubbo时，可以不需要这个
  protocol:
    name: dubbo
    port: -1 # 服务在dubbo中端口号,-1代表自动分配
  monitor:
    protocol: registry # 自动注册dubbo的monitor
  consumer:
    check: false # 启动检查有没有提供者
    timeout: 12000 # 消费者调用超时时间
    retries: 1 # 调用失败重试次数，不包含第一次调用
    version: 1.0.0 # 统一调用版本服务，实现灰度发布
    loadbalance: roundrobin # 负载均衡。random：权重随机，roundrobin：权重轮询，leastactive：速度最快优先，consistenthash：一致性哈希

#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000 # 设置hystrix的超时时间，默认1000ms
#      circuitBreaker:
#        enabled: true # 确定断路器是否用于跟踪运行状况和短路请求（如果跳闸）。默认true
#        sleepWindowInMilliseconds: 5000 # 熔断多少秒后去尝试请求，默认5s
#        errorThresholdPercentage: 50 # 失败率达到多少百分比后熔断，默认50%
#        requestVolumeThreshold: 20 # 熔断触发的最小个数/10s，默认20
#        forceOpen: false # 属性如果为真，强制断路器进入打开（跳闸）状态，其中它将拒绝所有请求。默认false，此属性优先于circuitBreaker.forceClosed
#        forceClosed: false # 该属性如果为真，则迫使断路器进入闭合状态，其中它将允许请求，而不考虑误差百分比。默认false，如果是强依赖，应该设置为true，circuitBreaker.forceOpen属性优先，因此如果forceOpen设置为true，此属性不执行任何操作。

# spring相关
spring:
  aop:
    auto: true # 开启spring aop

  cache:
    type: redis # 指定spring缓存为redis

  devtools: # spirng热部署
    restart:
      enabled: true # 设置开启热部署
      additional-paths: src/main/java # 重启目录
      exclude: WEB-INF/**

  redis:
    database: 0 # redis 数据库索引（默认为0）
    host: 47.101.135.160
    password: root # redis 服务器连接密码（默认为空）
    port: 6379
    timeout: 12000  # 连接超时时间（毫秒），默认2000ms
      # cluster:
      # nodes: 192.168.211.134:7000,192.168.211.134:7001,192.168.211.134:7002
    # maxRedirects: 6
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接

# 打印日志统一根路径
log:
  file: /root/project/log/dubbo-web/prod
